/**:
  ros__parameters:
  # Kvaser node parameters
    hardware_id: 22024
    circuit_id: 0
    bit_rate: 500000
    enable_echo: false
  # DBW CAN node
    max_steer_angle: 470.0
    max_dump_angle: 100.0
    max_articulation_angle: 90.0
